### ISSUE TITLE
Enforce stricter base configuration ?

### ISSUE THREAD

**Issue by Julien-R44** [AdonisCommunity/adonis-preset-ts#11]
I think it would be nice to enable stricter typescript mode on this config. It would enforce better practices in the community, and obviously, it would allow people to avoid more bugs. 

I am very much in favor of always having a very strict configuration, whether it be ESLint or Typescript.

This would obviously be a big breaking change.

I wondered if there were technical reasons for not doing it, or if it was just a personal preference? 
Let me know if you guys have any opinions on this.

cc @RomainLanz @targos @thetutlage

**Comment by targos** [comment]
I also favor strict configurations by default. I cannot really speak about this preset as I don't use it in my projects. Do you have specific rules in mind that you think should be enabled?

**Comment by Julien-R44** [comment]
Personally, I usually try to activate almost all strict rules on my TS projects.

So, IMO, all rules that come with `strict: true` should be enabled. For example, `noImplicitAny`, is missing from this configuration, and is an essential rule, I think, if not the most important.

Then there are other nice rules, but I don't know if it's worth integrating them in the default configuration of an Adonis project. This could be very annoying for some beginners ( I am thinking in particular of `noUncheckedIndexedAccess` )

**Comment by targos** [comment]
> For example, noImplicitAny, is missing from this configuration, and is an essential rule, I think, if not the most important.

Agreed. To me, a project without `noImplicit` any is almost as unsafe as a project without TypeScript ^^

I would disable `useUnknownInCatchVariables` by default because it's not easy to work with it IMO.

> I am thinking in particular of `noUncheckedIndexedAccess`

I think this shouldn't be enabled by default. Even as a non-beginner I don't have this rule. There are way too many things to check when it's enabled.

**Comment by thetutlage** [comment]
I have abused the TypeScript type system with Lucid and that is when I opted out of the strict mode. 

However, as I am refactoring packages for v6 (ESM Only), I will opting for strict mode of TypeScript. Let's see if come up with any challenges and then we can discuss them here

**Comment by targos** [comment]
I think the preset we recommend for users shouldn't necessarily have the same constraints as the one used by the project's packages.

**Comment by thetutlage** [comment]
Wouldn't strict mode break if the installed packages are not meant to work with strict mode?

**Comment by targos** [comment]
`skipLibCheck` takes care of that issue.

**Comment by thetutlage** [comment]
> `skipLibCheck` takes care of that issue.

If that's the case, then we can recommend a strict `tsconfig.json` file. However, as @Julien-R44 going to be a breaking change right now. How about recommending it with the next major release?

Also, while we are on this topic. Can you share the ideal `tsconfig.json` file you guys use?

This is what I am using right now. https://github.com/adonisjs/env/blob/next/tsconfig.json

**Comment by Julien-R44** [comment]
I would just add these rules :

```
"strict": true,
"allowUnreachableCode": false,
"allowUnusedLabels": false,
"useUnknownInCatchVariables": false,
```

And I think we're pretty good. A good balance between too strict and not strict enough

**Comment by targos** [comment]
```
"allowUnreachableCode": false,
"allowUnusedLabels": false,
```

I think this kind of rules are better served by ESLint configurations but I won't block it.

**Comment by Julien-R44** [comment]
Also, I totally agree with recommending the new config only from Adonis 6. 

I think it would also be cool to propose a stricter eslint config for Adonis 6 too. But I think that's a much more divisive issue. We could include eslint-plugin-unicorn, eslint-plugin-n, eslint-plugin-import etc.. 

I'm a real ESlint fan but I can understand that it makes some people uncomfortable and not sure if it's a good idea to include it by default. 
Will open an issue on https://github.com/adonisjs-community/eslint-plugin-adonis

**Comment by thetutlage** [comment]
Sure, feel free to recommend. I have documented my rules/conventions here. https://github.com/thetutlage/meta/discussions/3

**Comment by thetutlage** [comment]
Was going through the options enabled by the `strict` flag. I think, we might not be able to use `strictPropertyInitialization` with Lucid models

**Comment by RomainLanz** [comment]
I am all into having stricter rules by default.

Concerning `strictPropertyInitialization`, it would work if we defined the correct typing.
We are assuming that the model fields are always defined, but that may not be the case.

```ts
const user = new User()
```

In this example, the fields would be `undefined`.
We could initialize them to `null` dynamically based on the column decorator, but TypeScript will not catch that.

**Comment by targos** [comment]
Lucid models are quite unsafe from a typing perspective and I'd be happy if it could be improved :)

**Comment by thetutlage** [comment]
It will be nightmare to make all the columns on the model typed to `null` or `undefined`. You will have to always the null coalescing operator `?` or non-null assertion operator `!`.

> Lucid models are quite unsafe from a typing perspective and I'd be happy if it could be improved :)

@targos. Open for suggestions 👍

**Comment by targos** [comment]
I have some Lucid-related feedback on my todo list but it's out of scope for this issue. I think we should keep `strictPropertyInitialization` off for now.

**Comment by thetutlage** [comment]
> I have some Lucid-related feedback on my todo list but it's out of scope for this issue

You can share that with me over Discord and then I can refine them as I see fit
